=== Jastiva/wograld/javaeditor/trunk/resource/system/dtd/GameObjectMatchers.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Gridarta MMORPG map editor for Crossfire, Daimonin and similar games.
  ~ Copyright (C) 2000-2011 The Gridarta Developers.
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License along
  ~ with this program; if not, write to the Free Software Foundation, Inc.,
  ~ 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  -->

<!ENTITY % Match "(And|Or|Attrib|TypeNrs)">
<!ENTITY % Matches "%Match;+">

<!ELEMENT GameObjectMatchers (GameObjectMatcher+)>
<!ELEMENT GameObjectMatcher (title+,Env?,%Match;)>
<!ATTLIST GameObjectMatcher
    id CDATA #IMPLIED
    system (true|false) 'false'
>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
    xml:lang CDATA #REQUIRED
>

<!ELEMENT Env ((%Match;)?)>

<!ELEMENT And (%Matches;)>
<!ELEMENT Or (%Matches;)>

<!ELEMENT Attrib EMPTY>
<!ATTLIST Attrib
    useArchetype (true|false) 'true'
    name NMTOKEN #REQUIRED
    value CDATA '1'
    type (string|int) 'string'
    op (eq|ne|ge|gt|le|lt) 'eq'
>

<!ELEMENT TypeNrs EMPTY>
<!ATTLIST TypeNrs
    numbers CDATA #REQUIRED
>

=== Jastiva/wograld/javaeditor/trunk/test-mapvalidator/atrinik/arch/dev/editor/conf/GameObjectMatchers.xml
<?xml version="1.0"?>
<!--
  ~ Gridarta MMORPG map editor for Crossfire, Daimonin and similar games.
  ~ Copyright (C) 2000-2011 The Gridarta Developers.
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License along
  ~ with this program; if not, write to the Free Software Foundation, Inc.,
  ~ 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  -->

<!DOCTYPE GameObjectMatchers SYSTEM "GameObjectMatchers.dtd">
<GameObjectMatchers>
	<!-- Objects to be put below the floor in insertion tool -->
	<GameObjectMatcher id="system_below_floor" system="true">
		<title xml:lang="en">Below Floor</title>
		<TypeNrs numbers="-666" />
	</GameObjectMatcher>

	<!-- Objects to be put below the floor in insertion tool -->
	<GameObjectMatcher id="system_wall" system="true">
		<title xml:lang="en">Wall</title>
		<And>
			<TypeNrs numbers="77 79" />
			<Attrib name="no_pass" type="int" op="ne" value="0" />
		</And>
	</GameObjectMatcher>

	<!-- Objects to be treated as monsters in insertion tool -->
	<GameObjectMatcher id="system_monster" system="true">
		<title xml:lang="en">Monster</title>
		<TypeNrs numbers="80 81 83" />
	</GameObjectMatcher>

	<!-- Objects to be treated as exits by the GUI -->
	<GameObjectMatcher id="system_exit" system="true">
		<title xml:lang="en">Exit</title>
		<TypeNrs numbers="41 66 69 94 95" />
	</GameObjectMatcher>

	<!-- Objects to be checked by the "Critical slaying characters" map
		 validator. -->
	<GameObjectMatcher id="system_environment_sensor" system="true">
		<title xml:lang="en">Environment Sensor</title>
		<TypeNrs numbers="133" />
	</GameObjectMatcher>

	<GameObjectMatcher id="system_monster_only" system="true">
		<title xml:lang="en">Monster Only</title>
		<TypeNrs numbers="80 83" />
	</GameObjectMatcher>

	<GameObjectMatcher id="system_combat_values_objects" system="true">
		<title xml:lang="en">Objects using &quot;combat_values&quot;</title>
		<TypeNrs numbers="5 6 7 13 39 54 62 72 73 80 83 154 158" />
	</GameObjectMatcher>

	<!-- Objects checked by the "Suspicious connection" map validator: objects
		 matching this matcher are connection sources. -->
	<GameObjectMatcher id="system_connection_source" system="true">
		<title xml:lang="en">Connected objects being a source</title>
		<TypeNrs numbers="17 18 27 30 31 32 51 64 92 93 132 133 134" />
	</GameObjectMatcher>

	<!-- Objects checked by the "Suspicious connection" map validator: objects
		 matching this matcher are connection sinks. -->
	<GameObjectMatcher id="system_connection_sink" system="true">
		<title xml:lang="en">Connected objects being a sink</title>
		<Or>
			<TypeNrs numbers="26 41 42 55 62 65 74 78 81 91 94 98 112 132" />
		</Or>
	</GameObjectMatcher>

	<!-- Objects checked by the "Suspicious connection" map validator: objects
		 matching this matcher are connection sinks. This matcher exists in
		 order to match inventory objects since &lt;Env&gt; cannot be included
		 into &lt;Or&gt;. -->
	<GameObjectMatcher id="system_connection_sink2" system="true">
		<title xml:lang="en">Connected objects being a sink</title>
		<TypeNrs numbers="-666" />
	</GameObjectMatcher>

	<!-- Objects checked by the "Shop square contains paid item" map validator:
		 objects matching this matcher are paid items. -->
	<GameObjectMatcher id="system_paid_item" system="true">
		<title xml:lang="en">Paid items</title>
		<And>
			<Attrib name="unpaid" type="int" value="0" />
			<Attrib name="no_teleport" type="int" value="0" />
			<Attrib name="monster" type="int" value="0" />
			<Attrib name="weight" type="int" op="ne" value="0" />
		</And>
	</GameObjectMatcher>
</GameObjectMatchers>

=== Jastiva/wograld/javaeditor/trunk/test-mapvalidator/daimonin/arch/dev/editor/conf/GameObjectMatchers.xml
<?xml version="1.0"?><!--
  ~ Gridarta MMORPG map editor for Crossfire, Daimonin and similar games.
  ~ Copyright (C) 2000-2011 The Gridarta Developers.
  ~
  ~ This program is free software; you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation; either version 2 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License along
  ~ with this program; if not, write to the Free Software Foundation, Inc.,
  ~ 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  -->

<!DOCTYPE GameObjectMatchers SYSTEM "GameObjectMatchers.dtd">
<GameObjectMatchers>

    <GameObjectMatcher id="system_floor" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="65 68 71"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_below_floor" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="-666"/>
        <!-- <Attrib name="layer" value="0" /> -->
    </GameObjectMatcher>

    <GameObjectMatcher id="system_wall" system="true">
        <title xml:lang="en">T</title>
        <And>
            <TypeNrs numbers="77"/>
            <Attrib name="layer" type="int" value="7" op="ne"/>
        </And>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_monster" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="80 81 83"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_exit" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="41 66 69 94 95"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_environment_sensor" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="133"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_monster_only" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="80 83"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_combat_values_objects" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="5 6 7 13 39 54 62 72 73 80 83 154 158"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_connection_source" system="true">
        <title xml:lang="en">T</title>
        <TypeNrs numbers="17 18 27 30 31 32 51 64 92 93 132 133 134"/>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_connection_sink" system="true">
        <title xml:lang="en">T</title>
        <Or>
            <TypeNrs numbers="26 41 42 55 62 65 74 78 81 91 94 98 112 132"/>
        </Or>
    </GameObjectMatcher>

    <GameObjectMatcher id="system_connection_sink2" system="true">
        <title xml:lang="en">T</title>
        <Env/>
        <TypeNrs numbers="-666"/>
    </GameObjectMatcher>

</GameObjectMatchers>
